# -*- coding: utf-8 -*-
"""
Created on Wed May 13 19:28:26 2020

@author: Romain
CODE 10
"""
import transpo
import passwordcipher


CT = "REDWDKTIBJBSBMMFDBSMMCPCNMRQUKEJSNYNWLIMMPWQMRYXPBWSSDSIPKMNTDRXMQSMPBBEFFPSRSBXMRPNSNEQZKHMDKIXJWSIQRSRSCBNFSHXWMRSRSPSEDAIQXSXBPDAFPSFQSSSBREXQISPIQJKYWWRUEBXBEIMISJRJBLBQBUXWBBJIVBDSQBISYMXMKQFFSKSMKPHKKTXPERRVKTYKMSSLMRXIRRWFMSVSRIESUDX"

CT9 = "XBZPAFQVDOXZAAVVBVWTBDQQDEAVFEYEXQAYXYSPXLDYTDWLFVYYYDDOWNVWYEDAWPELBWVVDWLZESVXYBDDHDDTEQQFDWHOWEQVCDNYLQEW"

CTP = "HJNDMSGHPQFWQUCACPGJGLPEHNHHVCOENCERLLOUHUARGGNPLLMRNEUCNSGOJLPPRRFPOLQHCMPJPLCOWGQHONCOQQYNAOOCMLCLHFLZNLEOOQCLLMPQPNMNWLMELLLNRMPOHOCTYGCUCHIPWPLLCNGHAOFTPFGHHXNWPRNPPSHICQCCUDYXEMYHUHNTHHGHAGCLNXENFFYJGOESPWCWGUGXUQLLHNOQWMNCQNSECXNQEPSGNJNAHMFQTNFXPLHJRNPCGMGUNOEDCXCGHCHHVMPHPPUAYLGX"

grid, text = transpo.crypta_transpo(CT9)

PTi = {}
textPT = {}
score = {}

results = {}
#passwordcipher.bf(text[(15,16)])
#result = passwordcipher.man_bf(text[(15,16)], "beetles")

finalG, finalT = transpo.crypta_transpo(result)



for i in text:
    results[i] = passwordcipher.bf(text[i])
    


    
    
    
    